services:
  webshop-products:
    image: webshop-products
    env_file: ./.env.mysql
    environment:
      - DB_HOST=db-products
      - MYSQL_DATABASE=products
      - DB_PORT=3306
    ports:
    - "8081:8081"
    networks:
      - backend-tier
      - front-tier
  webshop-categories:
    image: webshop-categories
    env_file: ./.env.mysql
    environment:
      - DB_HOST=db-categories
      - DB_PORT=3307
      - MYSQL_DATABASE=categories
    ports:
      - "8082:8082"
  db-products:
    image: mysql:8.2.0-oraclelinux8
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - "./.env.mysql"
    environment:
      - MYSQL_DATABASE=products
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - "./db/sql/products:/docker-entrypoint-initdb.d"
      - "./db/data/products:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - backend-tier
  db-categories:
    image: mysql:8.2.0-oraclelinux8
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - "./.env.mysql"
    environment:
      - MYSQL_DATABASE=categories
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_TCP_PORT=3307
    volumes:
      - "./db/sql/categories:/docker-entrypoint-initdb.d"
      - "./db/data/categories:/var/lib/mysql"
    ports:
      - "3307:3307"
    networks:
      - backend-tier
networks:
  backend-tier:
  front-tier: