version: '3.2'
services:
  legacywebshop:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8080"
    networks:
      local_dev_net:
          aliases:
              - legacywebshop

  web-shop-db-image:
    build:
      context: ./
      dockerfile: ./docker/DockerfileMySQL
    volumes:
      - "./.data:/var/lib/mysql"
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image

  web-shop-products:
    build:
      context: ../eshop_products/
      dockerfile: ./Dockerfile
    command: tail -f /dev/null
    environment:
      DB_HOST: web-shop-db-image
    ports:
      - "8081:8081"
    networks:
        local_dev_net:
            aliases:
                - web-shop-products
  web-shop-categories:
    build:
      context: ../eshop_categories/
      dockerfile: ./Dockerfile
    command: tail -f /dev/null
    environment:
      DB_HOST: web-shop-db-image
      MY_POD_NAME: abc123
    ports:
      - "8082:8082"
    networks:
        local_dev_net:
            aliases:
                - web-shop-categories
networks:
  local_dev_net:
    driver: bridge
