apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    app: apache
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: apache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  selector:
    matchLabels:
      app: apache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: apache:latest
        name: apache
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: apache
